[providers]
providers = ['php']

[phases.setup]
nixPkgs = [
    'php82',
    'php82Packages.composer',
    'postgresql'
]

[phases.build]
cmds = [
    'composer install --no-interaction --prefer-dist'
]

[nixPkgs]
php82 = { extensions = ["pdo_pgsql", "pgsql"] }