import 'package:flutter/material.dart';

Future<bool?> showTermsDialog(BuildContext context) {
  bool agreed = false;

  return showDialog<bool>(
    context: context,
    barrierDismissible: false,
    builder: (context) {
      return StatefulBuilder(
        builder: (context, setState) {
          return Dialog(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(22),
            ),
            child: SizedBox(
              width: 420,
              height: 520,
              child: Padding(
                padding: const EdgeInsets.all(22),
                child: Column(
                  children: [
                    /// Header
                    const CircleAvatar(
                      radius: 28,
                      backgroundColor: Color(0xFFE8F5E9),
                      child: Icon(
                        Icons.description_rounded,
                        color: Color(0xFF3AA76D),
                        size: 30,
                      ),
                    ),

                    const SizedBox(height: 15),

                    const Text(
                      "Terms & Conditions",
                      style: TextStyle(
                        fontSize: 22,
                        fontWeight: FontWeight.bold,
                      ),
                    ),

                    const SizedBox(height: 6),

                    const Text(
                      "Please read before creating your account.",
                      style: TextStyle(color: Colors.grey, fontSize: 13),
                    ),

                    const SizedBox(height: 20),

                    /// Terms Card
                    Expanded(
                      child: Container(
                        padding: const EdgeInsets.all(18),
                        decoration: BoxDecoration(
                          color: const Color(0xFFF8FBF9),
                          borderRadius: BorderRadius.circular(15),
                          border: Border.all(color: Colors.green.shade100),
                        ),
                        child: const SingleChildScrollView(
                          child: Text('''
Welcome to CarbonWise!

By creating an account, you agree to the following:

• Provide accurate personal information.

• CarbonWise collects your Name, Student Number, G-Suite Email, Department, Campus, Profile Picture (optional), and Carbon Emission Records.

• Your information will only be used for:

   • Carbon emission tracking

   • CarbonWise score computation

   • Rankings

   • Reports

   • AI Forecasting

   • Academic research

• Your personal information will not be shared with unauthorized third parties.

• Carbon forecasts generated by the AI are estimates and should only be used as guidance.

• By continuing, you acknowledge that you have read and accepted these Terms and Conditions.
''', style: TextStyle(fontSize: 13, height: 1.55)),
                        ),
                      ),
                    ),

                    const SizedBox(height: 15),

                    CheckboxListTile(
                      value: agreed,
                      contentPadding: EdgeInsets.zero,
                      controlAffinity: ListTileControlAffinity.leading,
                      activeColor: const Color(0xFF3AA76D),
                      title: const Text(
                        "I have read and agree to the Terms & Conditions",
                        style: TextStyle(fontSize: 13),
                      ),
                      onChanged: (value) {
                        setState(() {
                          agreed = value!;
                        });
                      },
                    ),

                    const SizedBox(height: 10),

                    Row(
                      children: [
                        Expanded(
                          child: OutlinedButton(
                            onPressed: () {
                              Navigator.pop(context, false);
                            },
                            style: OutlinedButton.styleFrom(
                              minimumSize: const Size.fromHeight(48),
                              side: const BorderSide(color: Color(0xFF3AA76D)),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: const Text("Cancel"),
                          ),
                        ),

                        const SizedBox(width: 12),

                        Expanded(
                          child: ElevatedButton(
                            onPressed: agreed
                                ? () {
                                    Navigator.pop(context, true);
                                  }
                                : null,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: const Color(0xFF3AA76D),
                              minimumSize: const Size.fromHeight(48),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: const Text(
                              "I Agree",
                              style: TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          );
        },
      );
    },
  );
}
